### ISSUE TITLE
T1M bug: Some mutants less explosive than expected | Atlantis

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#760] opened 2023-03-13 10:48 UTC
I'm currently doing a playthrough and came across a hatched flying mutant that didn't explode much after killing it.  I'll keep an eye out whether this bug occurs again.

Tomb1Main video: https://youtu.be/f9fb-cm0C_Y

TombATI video: https://youtu.be/11_ghT0Vf_Y

Saves: https://drive.google.com/drive/folders/1WZlt9iGwtASVM_dlwBrkQVYKOhh-gTFY?usp=sharing

**Comment by walkawayy** [comment] 2023-03-13 12:28
I'm guessing this is related to #623.

**Comment by aredfan** [comment] 2023-03-13 13:56
Yeah this bug isn't a one-off.  I've made another video with the first half showing that using a shotgun leads to no explosion.  The second half of the video shows using uzis causes a moderately small explosion instead.

https://youtu.be/DRWJpE3v8-Q

**Comment by walkawayy** [comment] 2023-03-21 01:15
Gonna close this since it's due to #623 confirmed by @aredfan `I've tested this exe in Atlantis and the mutants are back to being explosive as ever 👍`.

**Closed as completed by walkawayy** 2023-03-21 01:15 UTC
Labels: TRX bug, TR1
