### ISSUE TITLE
The game is not closed.

### ISSUE THREAD

**Issue by antonio3687** [LostArtefacts/TRX#2033] opened 2024-12-13 21:09 UTC
[video.webm](https://github.com/user-attachments/assets/fe236e6d-c20f-4ab3-962d-6d321e8f341a)
Good evening, when I close the game it gets stuck as you can see in the video I have attached. Have you fixed the coliseum textures? Thank you very much.

**Comment by lahm86** [comment] 2024-12-13 21:44
~~It looks like the game is getting stuck somewhere. Can you load the gym level? Or can you try loading other levels with the console e.g. `/play 2` to start Vilcabamba. Do you possibly have customized FMVs in place?~~
I misunderstood, I see that it gets stuck when you close it. Could you attach your log file? It may offer a hint.

Could you elaborate on what you mean by fixing the Colosseum textures?

**Comment by antonio3687** [comment] 2024-12-14 00:07
[TR1X.zip](https://github.com/user-attachments/files/18132990/TR1X.zip)
Hello, it creates a LOG file of 86,4 megas, I had to compress it to be able to upload it. The textures of the coliseum I attach it in a screenshot. Greetings.
![390907554-de1fd629-3433-4995-8ffc-f9ed685ffd78](https://github.com/user-attachments/assets/4a41f0e1-5ddd-42d9-aa55-0082dd2c9ce2)

**Comment by aredfan** [comment] 2024-12-14 08:09
I can reproduce this issue too, it only happens when FMVs are enabled.

**Comment by lahm86** [comment] 2024-12-14 10:06
Thanks @antonio3687 and @aredfan. Fix is under review.

Regarding the textures in Colesseum, yes, we fixed the original issue there on the roof (aredfan also commented on this [here](https://github.com/LostArtefacts/TRX/issues/1971#issuecomment-2506787268), perhaps you missed it). You can check the discussion below and the original issue for more details.

https://github.com/LostArtefacts/TRX/discussions/736
https://github.com/LostArtefacts/TRX/issues/131

**Closed as completed** 2024-12-14 11:31 UTC
Labels: TRX bug, Unreleased, TR1
