### ISSUE TITLE
TRX detected as malware by Windows Defender, Virus Total and Firefox

### ISSUE THREAD

**Issue by Nangt3c** [LostArtefacts/TRX#1966] opened 2024-11-28 04:54 UTC
TR1X zip file detected as a Trojan by Windows Defender, same for TR2X
![imagen](https://github.com/user-attachments/assets/1cdc17a0-370f-474b-8a4e-b32c5935b9c5)

**Comment by Richard-L** [comment] 2024-11-28 06:43
#909

**Comment by rr-** [comment] 2024-11-28 09:00
Thank you for the report. I'll close it as a duplicate of #909 which we hope to work on soon.

**Closed as completed by rr-** 2024-11-28 09:00 UTC
Labels: Duplicate
