### ISSUE TITLE
Request: Support for ogg and mp3 soundtrack

### ISSUE THREAD

**Issue by aorin1** [LostArtefacts/TRX#794] opened 2023-03-30 14:46 UTC
Currently, only FLAC is supported

**Comment by walkawayy** [comment] 2023-03-30 17:36
I thought support for this was added in version 2.13 in #688. Did you try in the latest version?

**Comment by aorin1** [comment] 2023-03-30 17:48
> I thought support for this was added in version 2.13 in #688. Did you try in the latest version?

I did today with version 2.13.2 and tried mp3 and ogg tracks inside the music folder, only putting back the flac files reproduce jingles, background sound and music. Unless there's a very specific way to make both formats working that I'm not aware of.

**Comment by Richard-L** [comment] 2023-03-30 20:16
I also couldn't get a different media container to work but thought it was likely just a naming scheme problem.

**Comment by walkawayy** [comment] 2023-03-30 20:18
@carlo-bramini do you have any ideas? Tagging since you wrote the feature.

**Comment by carlo-bramini** [comment] 2023-04-03 15:29
> @carlo-bramini do you have any ideas? Tagging since you wrote the feature.

Yes, the ogg/mp3 files have been saved in planar format.
As you can see here:
https://github.com/LostArtefacts/Tomb1Main/blob/841599c62eb2ab5047e76e8ef700547b0fb890ae/src/specific/s_audio.c#L94
at the time of writing, the engine supports:

- AV_SAMPLE_FMT_U8
- AV_SAMPLE_FMT_S16
- AV_SAMPLE_FMT_S32
- AV_SAMPLE_FMT_FLT

but it does not support these one:

- AV_SAMPLE_FMT_U8P
- AV_SAMPLE_FMT_S16P
- AV_SAMPLE_FMT_S32P
- AV_SAMPLE_FMT_FLTP

More details on those types can be found here:
https://ffmpeg.org/doxygen/3.1/group__lavu__sampfmts.html

In my opinion, if you really want to use other file formats, the fastest solution is to save the audio files with samples in interleaved mode rather than planar mode.
A more complicated solution could be to write a piece of code for manually merging the planar samples for left and right channel in interleaved mode, but I don't know if it is worth to do so.

**Comment by aorin1** [comment] 2023-04-03 18:36
I'm not an expert, so I can't tell the difference, does the reply above mean that the user needs to convert the lossless flac to a specific mp3 or ogg container that are different than the normal converters around? I've tried three different software to convert those to either mp3 or ogg, being ffmpeg itself and Audacity without success, the engine will only reproduce the flac files.
Tomb2Main supports normal mp3 and ogg files.

**Comment by rr-** [comment] 2023-04-04 21:55
Since we're the only project to use ffmpeg which was a decision made to maximize compatibility with third party containers, I think it's worth pursuing adding the conversion code.

**Comment by carlo-bramini** [comment] 2023-04-05 09:16
> Since we're the only project to use ffmpeg which was a decision made to maximize compatibility with third party containers, I think it's worth pursuing adding the conversion code.

Perhaps, libswresample can do it for us with little effort.

**Comment by rr-** [comment] 2023-04-05 11:09
> Since we're the only project to use ffmpeg which was a decision made to maximize compatibility with third party containers, I think it's worth pursuing adding the conversion code.

Clarification, because I was in a hurry when writing the original comment – I meant that it's worth to add this function for two reasons, first being of course the usability and compatibility with various formats, and the other about paving the way for other projects that might want to fork/reference our code, to make it more thorough/universal.

**Comment by Gerwin2k** [comment] 2023-09-12 15:25
What I find odd is this:
I have set of custom ffmpeg dll libraries supporting popular game-related formats including mp3 and ogg.
When I run a dynamically linked ffplay.exe (the stock ffmpeg command line player) with those libraries: I can play mp3 and ogg, no problems.
When I have a dynamically linked Tomb1main.exe combined with those libraries: the same mp3 and ogg files give silence.

**Comment by rr-** [comment] 2024-07-23 20:54
Turns out this was a problem with the way we decoded the audio, which got fixed in https://github.com/LostArtefacts/libtrx/commit/23fa9475e26dad14de3d28a84199f1e1b557034e (TR1X 4.2). Currently waiting for Danath to confirm.

**Comment by rr-** [comment] 2024-07-24 08:14
Danath confirmed the files work for him.

**Closed as completed by rr-** 2024-07-24 08:14 UTC
Labels: TRX bug, TR1
