### ISSUE TITLE
Tomb Raider error shader compilation failed Error 0:4 location syntax error parse error

### ISSUE THREAD

**Issue by Checkm8ra1n** [LostArtefacts/TRX#764] opened 2023-03-13 15:04 UTC
Can I resolve this??

**Comment by vvs-** [comment] 2023-03-13 16:19
Your driver probably misses a required OGL extension.

To make any sense of this message there is not enough context information. What is your GPU? What is your OS? What driver? Which driver version? Which T1M version?

Please, at least supply T1M log messages.

**Comment by Checkm8ra1n** [comment] 2023-03-13 16:45
That computer is old... 
GPU: Inter R HD graphics 1,7 GB
CPU: Intel Core i3 M380 2.53 Ghz
System: Windows 11
Driver of what??
Log: [Tomb1Main.log](https://github.com/LostArtefacts/Tomb1Main/files/10959595/Tomb1Main.log)

**Comment by vvs-** [comment] 2023-03-13 17:10
It's not supported. You should be definitely interested in reading #685

**Comment by rr-** [comment] 2023-03-28 15:53
Closing as a duplicate of #327

**Closed as completed by rr-** 2023-03-28 15:53 UTC
Labels: TR1
