### ISSUE TITLE
Assault course finish times aren't saved between game close and reopen

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#2168] opened 2024-12-30 17:11 UTC
Observed in build 265.

They are only saved whilst in the game.

**Comment by aredfan** [comment] 2024-12-30 17:19
Duplicate of #1578.

**Closed as not planned by aredfan** 2024-12-30 17:19 UTC
Labels: TRX bug, Duplicate, TR2

**Comment by Richard-L** [comment] 2024-12-30 17:24
Ah, thank you. I searched for:
- assault
- finish
- time
🙃
