### ISSUE TITLE
Include PS1 FMVs in installer?

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1364] opened 2024-05-07 13:04 UTC
Just a thought Dash, feel free to close if you'd rather not. But was thinking since the soundtrack is made available, and since TR1X nicely supports the PS1 video files that _are_ better quality, it would seem like a nice convenience to add them.

I tried compressing them and am coming to ~160mb.

**Comment by walkawayy** [comment] 2024-05-07 15:10
Gonna close as duplicate of #649.

**Comment by Richard-L** [comment] 2024-05-07 20:20
Ah, sorry.

**Closed as not planned** 2024-05-07 23:50 UTC
Labels: Feature, Data, TR1
