### ISSUE TITLE
Problem Running Tomb1Main

### ISSUE THREAD

**Issue by shykapil** [LostArtefacts/TRX#728] opened 2023-02-09 09:46 UTC
When I try to run Tomb1main, following error is shown
Shader compilation failed:
WARNING: 0:3: extension 'GL_EXT_gpu_shader4' is not supported
ERROR: 0:20: 'textureSize2D' : no matching overloaded functioø0

I have attached the Lof file as well, need help
Regards
[Tomb1Main.log](https://github.com/rr-/Tomb1Main/files/10695735/Tomb1Main.log)

**Comment by vvs-** [comment] 2023-02-09 15:22
Your graphics card is not supported. See #685

**Comment by shykapil** [comment] 2023-02-10 01:40
> Your graphics card is not supported. See #685

Thanks, But once it run without sound. Then I don't know what happened later.

**Comment by shykapil** [comment] 2023-02-10 01:43
According to thread reply, graphic card is not supported. there is a thread
how to edit Open_GL when graphic card is not supported, but I ddin't
understand the comments at all.
Regard.

**Comment by rr-** [comment] 2023-02-16 14:12
Closing as a duplicate of #685

**Closed as completed by rr-** 2023-02-16 14:12 UTC
Labels: TR1
