### ISSUE TITLE
Have Default config settings match vanilla behavior

### ISSUE THREAD

**Issue by OpenRift412** [LostArtefacts/TRX#1016] opened 2023-09-29 00:16 UTC
I think that while the additional QoL changes are nice, having most of the settings match how they would appear in vanilla TR1 by default makes the most sense, especially for new players.

**Comment by Richard-L** [comment] 2023-09-29 08:32
Isn't that the case mostly? Which settings are you referring to?

**Comment by OpenRift412** [comment] 2023-09-29 17:46
> Isn't that the case mostly? Which settings are you referring to?

I mean, I downloaded a fresh copy of Tomb1Main and it seems to have a lot of non-vanilla settings enabled out of the box (enhanced sidesteps, jumptwists, fix alligator AI, etc.)

**Comment by walkawayy** [comment] 2023-09-29 23:22
Gonna close this as a duplicate of #653. Which I just realized you also opened. 😆

**Closed as completed by walkawayy** 2023-09-29 23:22 UTC
Labels: Duplicate, TR1
