### ISSUE TITLE
Main Menu music doesn't loop

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1652] opened 2023-11-05 12:34 UTC
Currently once the track finishes, it does not start again.

I guess this is partly due to the missing demo modes https://github.com/LostArtefacts/TR2X/issues/7 where upon main menu return it restarts the music.

**Comment by aredfan** [comment] 2023-12-08 10:40
In my case, the demo mode does start when the Main Menu is idle for 30 seconds.

When the demo mode finishes and I get returned to the Main Menu, there's no music.  I've confirmed that the bug is caused by LostArtefacts/TRX#1614.

**Edit:** You're right - the Main Menu music doesn't loop.  I went onto the Main Menu and kept pressing left/right to prevent the demo mode from starting until the music track ended, to be sure.

**Comment by Richard-L** [comment] 2023-12-08 12:25
Thanks for investigating.

So something in my TR2X setup being wrong is why it doesn't play the demos? Guess I'm missing the files for them - will check. Either way, unrelated to this issue.

**Comment by aredfan** [comment] 2024-10-10 14:02
Fixed in one of the TR2X releases between 0.1 and 0.5.

**Closed as completed by aredfan** 2024-10-10 14:02 UTC
Labels: TRX bug, TR2
