### ISSUE TITLE
[Bug] Default Keybinds Override User Keybinds

### ISSUE THREAD

**Issue by OpenRift412** [LostArtefacts/TRX#652] opened 2022-11-21 16:55 UTC
If a key that already has a default bind is set to something else, the default bind overrides the custom bind. Shouldn't it be the other way around?

**Comment by walkawayy** [comment] 2022-11-21 17:02
I'm gonna close this as a duplicate of #564. A controls system rewrite is currently in progress, so this will hopefully be fixed soon.

**Closed as completed by walkawayy** 2022-11-21 17:02 UTC
Labels: Duplicate, TR1

**Comment by OpenRift412** [comment] 2022-11-22 01:51
> I'm gonna close this as a duplicate of #564. A controls system rewrite is currently in progress, so this will hopefully be fixed soon.

Will this rewrite include a sub-menu specifically for controller binds as well?

**Comment by walkawayy** [comment] 2022-11-23 01:10
Yes something will be done to
Make controllers customizable.
