### ISSUE TITLE
Bad RHW value causes graphics errors on Intel GPUs

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1574] opened 2024-09-09 20:04 UTC
See the white flickers in "User Keys", und "Back", and the "TR" missing in the bottom right version print.

https://github.com/user-attachments/assets/9ca77572-42b7-4708-8a4f-daee6e0442bd

**Comment by Richard-L** [comment] 2024-09-09 20:14
Actually I may have only noticed it in the controls menu. On a fresh start game start without any key conflicts, it also seems to do it just on the passport:


https://github.com/user-attachments/assets/27013273-de9d-4a92-af51-c8583660aa1c

**Comment by Richard-L** [comment] 2024-09-09 20:20
Okay, sorry to make a bit of a mess of this issue.... but this happens once the demo starts playing 😅 


https://github.com/user-attachments/assets/e0d55236-1b8c-41ed-b635-4e9ac8eb80ce

Once it finishes the screen stays black. The main menu doesn't seem to reappear.

**Comment by walkawayy** [comment] 2024-09-09 21:20
@Richard-L try this build and lmk if it fixes your issue

[laptop_v1 TR2X-0.2-432-gfc79d77-dirty-Windows.zip](https://github.com/user-attachments/files/16936758/laptop_v1.TR2X-0.2-432-gfc79d77-dirty-Windows.zip)

**Comment by Richard-L** [comment] 2024-09-10 20:46
@walkawayy No difference with your build sadly.

**Comment by walkawayy** [comment] 2024-09-10 20:47
I think this is caused by a bad reciprocal of homogenous w (RHW) value in `Output_CalcRoomVertices`.

**Comment by walkawayy** [comment] 2024-09-10 21:02
Can you try this one? @Richard-L 

[intel_v2 TR2X-0.2-439-gb708ab6-dirty-Windows.zip](https://github.com/user-attachments/files/16953703/intel_v2.TR2X-0.2-439-gb708ab6-dirty-Windows.zip)

**Comment by Richard-L** [comment] 2024-09-10 21:05
> Can you try this one? @Richard-L
> 
> [intel_v2 TR2X-0.2-439-gb708ab6-dirty-Windows.zip](https://github.com/user-attachments/files/16953703/intel_v2.TR2X-0.2-439-gb708ab6-dirty-Windows.zip)

With this one the flickering in the Main Menu remains, but the demo is black. I can hear the SFX of it running though.

**Comment by walkawayy** [comment] 2024-09-10 21:20
> > Can you try this one? @Richard-L
> > [intel_v2 TR2X-0.2-439-gb708ab6-dirty-Windows.zip](https://github.com/user-attachments/files/16953703/intel_v2.TR2X-0.2-439-gb708ab6-dirty-Windows.zip)
> 
> With this one the flickering in the Main Menu remains, but the demo is black. I can hear the SFX of it running though.

Can you start a new game and play The Great Wall and report what happens? And/or Lara's Home? I would be interested in normal gameplay not just demo. Also what level files are you using? Are they some super rare old files?

**Comment by Richard-L** [comment] 2024-09-10 21:27
Curiosly it's reproducing the same error now, whearas the demo just seems to stay black.

https://github.com/user-attachments/assets/ea0b0d08-cb40-49da-9e50-f3be7dc3333d

**Comment by rr-** [comment] 2024-12-12 00:36
@Richard-L can you try the dev snapshot from #1844  and let me know if it fixes this issue?

**Comment by Richard-L** [comment] 2024-12-12 20:54
Didn't find any build in your link but found this https://github.com/LostArtefacts/TRX/pull/2010#issuecomment-2539769537 and it works beautifully ❤️ 
More details on discord.

**Comment by rr-** [comment] 2024-12-12 22:20
Since #1844 got merged, we can close this.

**Closed as completed by rr-** 2024-12-12 22:20 UTC
Labels: OG bug, TR2
