### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by REF-2021** [LostArtefacts/TRX#644] opened 2022-11-03 09:29 UTC
Hi! I've installed the latest Tomb1Main, however when I try and launch it, an error message comes up 'Shader compilation failed: ERROR: 0:4: 'layout': syntax error syntax error'. Thanks very much for your help!

**Comment by Gerwin2k** [comment] 2022-11-03 12:35
The shader files have a syntax error indeed. They use v330 syntax, but identify as v130.
So it may work better by editing the shader files from 130 to 330, on the first line of the four shader files. (Attached as well)
[shaders_v330.zip](https://github.com/rr-/Tomb1Main/files/9928306/shaders_v330.zip)
Does it work with the attached shader files? 

See also issue #327

**Comment by REF-2021** [comment] 2022-11-03 14:13
Thanks! Works perfectly now :)

**Comment by shykapil** [comment] 2023-02-09 09:35
> The shader files have a syntax error indeed. They use v330 syntax, but identify as v130. So it may work better by editing the shader files from 130 to 330, on the first line of the four shader files. (Attached as well) [shaders_v330.zip](https://github.com/rr-/Tomb1Main/files/9928306/shaders_v330.zip) Does it work with the attached shader files?
> 
> See also issue #327

I have similar issue while running Tomb1Main, but error is as follow
Shader compilation failed:
WARNING: 0:3: extension 'GL_EXT_gpu_shader4' is not supported
ERROR: 0:20: 'textureSize2D' : no matching overloaded functioø0
Regards

**Comment by rr-** [comment] 2023-03-28 15:52
Closing as a duplicate of #327

**Closed as completed by rr-** 2023-03-28 15:52 UTC
Labels: Help wanted, TR1
