### ISSUE TITLE
Tihocan blade shadow too dark

### ISSUE THREAD

**Issue by Richard-L** [LostArtefacts/TRX#1264] opened 2024-04-03 21:12 UTC
TR1X https://github.com/LostArtefacts/TR1X/pull/1260#issuecomment-2034521418

https://github.com/LostArtefacts/TR1X/assets/4934209/8510cffd-6089-4819-9d3b-97d44d5fbe35

PS1

https://github.com/LostArtefacts/TR1X/assets/4934209/03773eb8-1045-4370-8645-4474c99c9f5c

It seems the shadow has the same transparency as Lara's shadow on the PS1, whilst on TR1X it is darker.

Dash I hope it's okay to compare to the PS1 version instead of TombATI. Imo it's by far the better version to compare against, and also much easier for me to handle and capture.

**Comment by rr-** [comment] 2024-04-03 21:21
>Dash I hope it's okay to compare to the PS1 version instead of TombATI. Imo it's by far the better version to compare against, and also much easier for me to handle and capture.

Yes, definitely. However since we're a port from PC, TR1X bugs are considered deviations from PC.

**Comment by lahm86** [comment] 2024-04-03 21:35
I think this is a duplicate of #879. Present in TombATI as well.

**Comment by rr-** [comment] 2024-04-03 21:40
Yes pretty sure that's the same thing. Closing as a duplicate.

**Closed as not planned by rr-** 2024-04-03 21:40 UTC
Labels: Duplicate, TR1
