### ISSUE TITLE
Feature request: Raise scion object to consistent position in inventory

### ISSUE THREAD

**Issue by aredfan** [LostArtefacts/TRX#321] opened 2022-01-12 16:22 UTC
Have anyone noticed that the scion object seems to be positioned rather low when viewed on the inventory?  I've made this image to show, as an example, that all plot items from Obelisk of Khamoon is just above the green line, but the scion is the exception.

![1](https://user-images.githubusercontent.com/94776985/149177061-9a33c94a-5864-422e-8e3c-2c0d059ea3e1.png)

**Comment by atombraiderfan** [comment] 2022-01-16 07:36
I've checked all the other plot items and I think I've jumped the gun here, some items are in consistent positions and others are low like the scion.  The other low items are listed below.

- Machine Cog
- Gold Bar
- Ankh (Sanctuary of the Scion)
- Fuse

On further reflection, since the issue isn't unique to the scion item, I think it's best to leave items as they are and close this ticket.

**Closed by atombraiderfan** 2022-01-16 07:36 UTC
Labels: Feature, Data, TR1
