### ISSUE TITLE
Graphical artifacts in Unfinished Business menus

### ISSUE THREAD

**Issue by Arthandas** [LostArtefacts/TRX#754] opened 2023-03-10 16:56 UTC
When you open any in-game menu (after loading a game, not from the main menu) and try to change or navigate the settings a 2D texture will be randomly overlaid over the screen.

This happens in **original** files, not the altered ones the installation guide links to.

![Tomb1Main 2023-03-10 17-50-23](https://user-images.githubusercontent.com/41027064/224376157-c302a7f5-defc-47ef-9a2f-46075315773d.png)

**Comment by walkawayy** [comment] 2023-03-10 21:17
Can you try the latest release [2.13.2](https://github.com/LostArtefacts/Tomb1Main/releases/tag/2.13.2) and see if that fixes it?

**Comment by Arthandas** [comment] 2023-03-11 11:00
I checked and the bug persists.

**Comment by lahm86** [comment] 2023-03-11 16:09
Would you be able to provide a level file that is affected by this so we can check the sprites @Arthandas?

**Comment by Arthandas** [comment] 2023-03-11 17:49
Here's the data folder extracted from the original TRUB3DFX.exe. You need to convert the .tubs to .phds with FexInspect to use with Tomb1Main.
I don't know if the bug exists in every level, I played only Egypt.
[DATA.zip](https://github.com/LostArtefacts/Tomb1Main/files/10949093/DATA.zip)

**Comment by Richard-L** [comment] 2023-03-11 22:14
I can't reproduce this using the retail UB files. I checked against your provided data and the `.TUB` seem to differ from retail `.PHD`s.

|Filename|CRC32|File Size|
|--- |--- |--- |
|CAT.PHD|3665762d|3,270,370|
|CAT.TUB|32b214d4|3,270,998|
|EGYPT.PHD|a426b92d|3,278,614|
|EGYPT.TUB|58497b84|3,279,242|
|END.PHD|cc0f7099|3,208,018|
|END.TUB|5a4284e7|3,208,018|
|END2.PHD|1d005c65|3,153,300|
|END2.TUB|78373aaf|3,153,300|

     


Maybe either something to do with how Fexinspect converts them, or with the 3DFX release of UB.

**Comment by vvs-** [comment] 2023-03-11 22:23
Don't forget that you can always use Internet Archive: https://web.archive.org/web/20030210153807/http://www.core-design.com:80/patches/trub3dfx.exe

It has nothing to do with Fexispect or 3DFX, all releases have identical files. You can use PHDs created by Core Design from Tomb Raider Gold: https://archive.org/details/TombRaiderGoldUSA

I can reproduce it in passport and only there.

EDIT: I'm taking back part about identical files. There are differences between TR Gold retail and downloadable version.

**Comment by Richard-L** [comment] 2023-03-11 22:35
@Arthandas Does the problem persist for you in either END or END2? The retail UB disc has both PHD and TUB of course, and latter two levels are identical to the ones you posted.

**Comment by walkawayy** [comment] 2023-03-11 22:37
Lahm found the .TUB level files have 108 font sprites and the .phd has 110. The two missing sprites are the left and right arrows, so it is spilling over into the next sequence (the right arrow is just blank?). So the menu arrow shows up as a pot sprite.

**Comment by walkawayy** [comment] 2023-03-11 22:45
@Arthandas is your intention to use Unfinished Business level files without music triggers? @Richard-L maybe you can link yours if so? The Gold levels are provided free of charge so it shouldn't be an issue. I don't know enough about all the level files out there to point in the right direction.

**Comment by Richard-L** [comment] 2023-03-11 23:03
Sure these are my files:

[ub-phd-retail.zip](https://github.com/LostArtefacts/Tomb1Main/files/10949660/ub-phd-retail.zip)

**Comment by vvs-** [comment] 2023-03-11 23:49
I think the best way to fix this for T1M is to bundle its own fonts, like some other engines do.

**Comment by Arthandas** [comment] 2023-03-11 23:57
> @Arthandas is your intention to use Unfinished Business level files without music triggers?

My intention was to use the original unmodded files as officially provided.

**Comment by lahm86** [comment] 2023-03-12 09:39
This can be closed as the files provided by @Richard-L can be used, which are effectively equivalent to what you have sourced - so the original levels without music, but they contain the sprites that are otherwise missing. Font work will be handled under #386 and #626.

![image](https://user-images.githubusercontent.com/33758420/224536121-fc7f92be-8d23-438c-8637-5987a40f7edc.png)

![image](https://user-images.githubusercontent.com/33758420/224536049-84cb9b81-7091-4299-8eaa-f3e20ae5391b.png)

**Closed as not planned by lahm86** 2023-03-12 09:39 UTC
Labels: TR1

**Comment by Arthandas** [comment] 2023-03-12 10:40
What is the source of those files?
They're not the same, for example, the file provided by Core Design uses a PC specific keyboard icon for controls instead of a portable console.

<img width="1370" alt="Tomb1Main 2023-03-12 11-35-54" src="https://user-images.githubusercontent.com/41027064/224539456-4780fd1d-0585-44dc-806e-022bb7427132.png">

**Comment by vvs-** [comment] 2023-03-12 13:27
There are lots of different retail versions of TR Gold even according to redump.org database: http://redump.org/discs/quicksearch/tomb-raider-gold/

As I've said before you can find those files on Internet Archive (see link above) and they can be easily verified by redump.org data.
